# Generated by Django 4.2.5 on 2023-10-02 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curd', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_info',
            new_name='UserInfo',
        ),
    ]
